Textobject selection queries
phaazon/kak-tree-sitter pull request #212
Opened 2024-01-22 19:06 UTC by topisani

First of all, sorry for the big refactors in unorganized commits

I based this on the `rewrite-tree-sitter-only` branch, as it included the beginings of some structures that are useful for this. I looked at doing highlighting with the same parser, but i think we would need to copy out most of `tree-sitter-highlight` to do that (which is what helix has done as well). This does however reuse the same parser for the document, so there is only two parsers per document.

I think this could also be the beginning of supporting incremental buffer updates. Kakoune should expose enough information to do this, and i think a generic system checking the timestamps and requesting a new buffer if it has changed would work.

Anyway, the main feature:

[![asciicast](https://asciinema.org/a/G8bYndRR6lDUiRiVczU2XLvb7.svg)](https://asciinema.org/a/G8bYndRR6lDUiRiVczU2XLvb7)

```
kak-tree-sitter-req-text-objects function.around
```

Current caveats:
 - there are no default mappings
 - it only supports one type of text object per call (i.e. no kak-tree-sitter-req-text-objects *.around)
 - It only supports extending the selection - no "forward to next function"
 - It cannot (easily) be used with the existing text objects as the reply comes asynchronously.
 - There is no command to list available text object types for a language

But, with some mappings, it is simple and works reliably.

Oh, and again, sorry for the giant single PR. I also fixed a bug where the request parser would fail if more than one request arrived at the same time. This would happen when the same buffer is open in two windows. I dont know if the way i fixed it is the best way, but now it will at least parse successive requests written to the same fifo.

Next up - indents?

2024-01-22 23:06 UTC, topisani commented
[![asciicast](https://asciinema.org/a/gyIJRFVbrqDslVlID7meaf5Rq.svg)](https://asciinema.org/a/gyIJRFVbrqDslVlID7meaf5Rq)

Changed the implementation to specifically support `map buffer object` modes. This means `<a-i>f` will now select inside a function. Also works with `<a-a>,{,[,],}` etc...

The function can no longer be called manually, as it requires `%val{object_flags}` and `%val{selection_mode}`, but that could be mitigated by writing a separate command in `static.kak` that sets those manually if needed. This seems like a reasonable default

2024-02-10 19:06 UTC, phaazon commented
I like that and I’ve been wanting to do that for a long time. As you said, the problem is that it’s not trivial to just rip off `tree-sitter-highlight` or come up with our own stuff. I do want something that basically:

1. Parses a buffer (with, indeed, partial updates support).
2. Make the tree available for both cursor traversal and highlight queries.

I haven’t looked at the content of your PR, yet — I plan on doing it right now — but first, I wanted to say thanks for trying to have a look at that. It’s the missing piece of KTS to me.

2024-02-12 15:33 UTC, topisani commented
Speaking of the work ive done on my develop branch, and important addition to this:

https://github.com/topisani/kak-tree-sitter/commit/bc1c2e4ceee935db35be777e31a4bc9976fee74c

2024-02-15 10:08 UTC, phaazon requested changes
Overall, I’m all in to merge this and start using all of that. It’s a missing piece of KTS to make it to the `v1.0` milestone. I have a couple of questions though. Also, it doesn’t have to be perfect before we merge it. I’m completely okay to open more `v0.*` versions until we reach a mature and stabilized enough experience.

Thanks very much for taking the time on doing all that! I have some parallel works to do but this is currently the most prioritized feature to merge in my mind as part of [v0.6](https://github.com/phaazon/kak-tree-sitter/milestone/2).

2024-02-15 10:08 UTC, phaazon commented on kak-tree-sitter/src/languages.rs
>    // NOTE: we need to keep that alive *probably*; better be safe than sorry
You can remove that comment if you use `ts_lang` now.

2024-02-15 10:08 UTC, phaazon commented on kak-tree-sitter/src/response.rs
> +    obj_type: String,
Should we make that an `enum`?

2024-02-15 10:08 UTC, phaazon commented on kak-tree-sitter/src/server.rs
> +    while de.end().is_err() {
I’m not sure why you switched to this pattern; may you explain a bit?

2024-02-15 10:08 UTC, phaazon commented on kak-tree-sitter/src/server.rs
> +        }
That logic should probably be moved into the handler / another method to lighten the current one.

2024-02-15 10:14 UTC, topisani commented on kak-tree-sitter/rc/static.kak
> +}
This uses the official (special) `objects` mode, that works with `<a-a>`, `<a-i>`, `[` etc, so i dont think it would work to use a custom user mode.

2024-02-15 10:16 UTC, topisani commented on kak-tree-sitter/src/handler.rs
> +    // Objects that contain the current selection and are not equal to it. This lets us call the function repeatedly to expand the selection
the innermost object that contains the entire selection. This behavior is consistent with `<a-a>(` etc. So this will always expand the current selection. The other behavior would be a command similar to `s`

2024-02-15 10:17 UTC, topisani commented on kak-tree-sitter/src/response.rs
> +    obj_type: String,
I considered it. We could, but its not technically required to be consistent across languages, so i dont see a reason to hard code it right now

2024-02-15 10:19 UTC, topisani commented on kak-tree-sitter/src/server.rs
> +    while de.end().is_err() {
Yes, this was an unrelated bugfix:
When two clients in the same kakoune session have the same buffer open, they both send highlighting requests on `NormalIdle`, and kakoune doesn't seem to close the file between the two calls to `echo -to-file`. Whatever the reason is, sometimes two requests arrive concattenated as one message. This parses that correctly, where before neither of the messages would be accepted.

2024-02-15 10:22 UTC, topisani commented on kak-tree-sitter/src/server.rs
> +        }
I restructured a lot of this on my develop branch, https://github.com/phaazon/kak-tree-sitter/compare/master...topisani:kak-tree-sitter:develop but im not entirely sure how we can merge those efforts

2024-02-15 10:25 UTC, topisani commented on kak-tree-sitter/src/server.rs
> +        }
I can open up a pull request for my develop branch if you're interested. I have done some refactors with the goal to make it easier to maintain, but there could be some things we disagree on, and its quite a bit of code to review

2024-02-17 12:40 UTC, phaazon commented
Superseded by #231.

2024-02-17 12:40 UTC, closed without merging